name: .NET

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
          include-prerelease: true
      
      - name: Move to right directory
        run: cd BlogEngine
      - name: Keep moving
        run: cd BlogEngine
      
      - name: Where are we
        run: pwd
        
      - name: What is there
        run: ls -lrt
    
      - name: Install dependencies
        run: dotnet restore ./BlogEngine.NET.csproj

      - name: Build with dotnet
        run: dotnet build BlogEngine.NET/BlogEngine.NET.csproj --configuration Debug

      - name: dotnet publish
        run: dotnet publish -c Debug -o ${{env.DOTNET_ROOT}}/myapp

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

